### ISSUE TITLE
Fail to run `azd up`

### ISSUE THREAD

**Issue by zimuli157** [Azure-Samples/java-on-aca-quarkus#3]
**Description**
An error occurred when running `azd up`, as follows:
![image](https://github.com/user-attachments/assets/c690cd7c-646c-4e2a-82a0-5ff0b493f674)

**Repro steps**
1. Run `azd auth login`.
2. Run `azd init --template Azure-Samples/java-on-aca-quarkus`.
3. Ensure that Docker is running in your environment.
4. Run `azd up`.

**Environment**

- azd version 1.10.3 (commit 0595f33fe948ee6df3da492567e3e7943cb9a733)
- OS: Windows

**Expected behavior**

Run `azd up` can successfully.

**Suggestion**
It was found that `telemetryId` was hard-coded in `main.bicep`. Suggest changing to variable.
![image](https://github.com/user-attachments/assets/84aa3f82-2eca-432c-9a0b-5d56af96b1cc)

@majguo and @hemarina for notification.

**Comment by majguo** [comment]
@zimuli157 The resource `telemetrydeployment` is removed from `main.bicep` in commit b221344, all issues reported in this ticket are fixed, pls have a retry, thanks.

**Comment by zimuli157** [comment]
It has been fixed and we will close this issue.
